import type { SiteContent } from "@/types/content";

export const fallbackContent: SiteContent = {
  nav: {
    links: [
      { key: "about", label_es: "sobre nosotros", label_en: "about" },
      { key: "menu", label_es: "menu", label_en: "menu" },
      { key: "experience", label_es: "la experiencia", label_en: "the experience" },
      { key: "events", label_es: "eventos", label_en: "events" },
      { key: "find", label_es: "encuentranos", label_en: "find us" },
    ],
    cta_es: "encuentranos",
    cta_en: "find us",
  },
  hero: {
    eyebrow_es: "· somos movimiento · somos pausa ·",
    eyebrow_en: "· we move · we pause ·",
    title1_es: "el cafe",
    title1_en: "the coffee",
    title2_es: "que camina",
    title2_en: "that walks",
    title3_es: "contigo",
    title3_en: "with you",
    foot_es: "calle tulipan 58 — abierto desde las 7:30",
    foot_en: "58 tulipan street — open from 7:30",
    ctaPrimary_es: "ver menu",
    ctaPrimary_en: "see menu",
    ctaSecondary_es: "como llegar",
    ctaSecondary_en: "directions",
    photoLabel_es: "foto: preparacion en barra",
    photoLabel_en: "photo: bar preparation",
  },
  about: {
    eyebrow_es: "sobre nosotros",
    eyebrow_en: "about us",
    title_es: "nacimos en la calle, en el transito cotidiano.",
    title_en: "born on the street, in the everyday walking.",
    body1_es:
      "Tulipan58 no fue pensado como destino final. Lo hicimos para acompanar — para caminar contigo mientras vas, mientras vuelves, mientras pausas.",
    body1_en:
      "tulipan58 was never meant to be a destination. We made it to accompany — to walk with you, on the way there, on the way back, on the pause.",
    body2_es:
      "Cafe de especialidad, hecho con cuidado, pensado para la vida real de todos los dias. Sin ceremonia.",
    body2_en:
      "Specialty coffee, made with care, for everyday real life. No ceremony.",
    pull_es: "Somos movimiento. Somos pausa. Somos comunidad.",
    pull_en: "We move. We pause. We are community.",
    stats: [
      { number: "58", label_es: "la calle que nos nombra", label_en: "the street that named us" },
      { number: "7:30", label_es: "abrimos, de lunes a sabado", label_en: "we open, mon-sat" },
      { number: "24 h", label_es: "reposo del cold brew", label_en: "cold brew rest time" },
    ],
  },
  menu: {
    eyebrow_es: "menu",
    eyebrow_en: "menu",
    title_es: "lo que servimos hoy.",
    title_en: "what we pour today.",
    note_es: "Grano de origen. Preparado como debe ser. Los precios son en pesos mexicanos.",
    note_en: "Single-origin beans. Made the way it should be. Prices are in mexican pesos.",
    cta_es: "menu completo",
    cta_en: "full menu",
    filterAll_es: "todo",
    filterAll_en: "all",
    filterHot_es: "caliente",
    filterHot_en: "hot",
    filterCold_es: "frio",
    filterCold_en: "cold",
    filterMethod_es: "metodo",
    filterMethod_en: "method",
    items: [
      { name_es: "espresso americano", name_en: "americano espresso", description_es: "doble, corto, honesto.", description_en: "double, short, honest.", price: 45, category: "hot", order: 1 },
      { name_es: "iced latte", name_en: "iced latte", description_es: "leche entera, hielo, espresso doble.", description_en: "whole milk, ice, double espresso.", price: 70, category: "cold", order: 2 },
      { name_es: "coldbrew horchata", name_en: "cold brew horchata", description_es: "24 h de reposo + horchata de casa.", description_en: "24h rest + house horchata.", price: 75, category: "cold", order: 3 },
      { name_es: "americano honey", name_en: "honey americano", description_es: "miel de abeja, doble espresso.", description_en: "bee honey, double espresso.", price: 55, category: "hot", order: 4 },
      { name_es: "cappuccino", name_en: "cappuccino", description_es: "espuma firme, cacao al final.", description_en: "firm foam, cocoa finish.", price: 60, category: "hot", order: 5 },
      { name_es: "flat white", name_en: "flat white", description_es: "ristretto doble, leche texturizada.", description_en: "double ristretto, textured milk.", price: 65, category: "hot", order: 6 },
      { name_es: "coldbrew caramelo", name_en: "caramel cold brew", description_es: "cold brew con salsa de caramelo.", description_en: "cold brew with caramel sauce.", price: 75, category: "cold", order: 7 },
      { name_es: "iced coffee vainilla", name_en: "vanilla iced coffee", description_es: "filtrado del dia, hielo, vainilla.", description_en: "day's filter, ice, vanilla.", price: 65, category: "cold", order: 8 },
      { name_es: "americano v60", name_en: "v60 americano", description_es: "metodo manual, taza llena, perfil limpio.", description_en: "pour-over, full cup, clean profile.", price: 80, category: "method", order: 9 },
    ],
  },
  experience: {
    eyebrow_es: "la experiencia",
    eyebrow_en: "the experience",
    title_es: "tres momentos. un mismo ritmo.",
    title_en: "three moments. one rhythm.",
    cards: [
      { tag_es: "para la manana", tag_en: "for the morning", title_es: "lunes temprano.", title_en: "early monday.", body_es: "El primer cafe del dia. Corto, tibio, para el camino.", body_en: "The first coffee of the day. Short, warm, for the road.", colorPair: "pair-tulipan", order: 1 },
      { tag_es: "para la pausa", tag_en: "for the pause", title_es: "media tarde.", title_en: "mid-afternoon.", body_es: "Cuando el dia pesa, el cafe camina contigo un rato mas.", body_en: "When the day weighs, coffee walks with you a little longer.", colorPair: "pair-bordo", order: 2 },
      { tag_es: "para estar", tag_en: "for staying", title_es: "quedarse.", title_en: "staying.", body_es: "Una silla, una mesa, el sol entrando por la ventana.", body_en: "A chair, a table, the sun coming in through the window.", colorPair: "pair-verde", order: 3 },
    ],
  },
  events: {
    eyebrow_es: "eventos · catering",
    eyebrow_en: "events · catering",
    title_es: "llevamos el cafe a tu lugar.",
    title_en: "we bring the coffee to your place.",
    body_es: "Bodas, oficinas, aperturas, domingos de mercado. Montamos una barra pequena, bien puesta, con el cafe que ya conoces.",
    body_en: "Weddings, offices, openings, sunday markets. We set up a small, well-done bar, with the coffee you already know.",
    bullets: [
      { text_es: "barra movil de cafe de especialidad", text_en: "mobile specialty coffee bar" },
      { text_es: "menu adaptado al evento", text_en: "menu tailored to the event" },
      { text_es: "reservas con dos semanas de anticipacion", text_en: "bookings two weeks ahead" },
    ],
    cta_es: "cuentanos de tu evento",
    cta_en: "tell us about your event",
  },
  statement: {
    body1_es: "el cafe",
    body1_en: "the coffee",
    body2_es: "que",
    body2_en: "that",
    body3_es: "camina",
    body3_en: "walks",
    body4_es: "contigo.",
    body4_en: "with you.",
    foot_es: "— tulipan58",
    foot_en: "— tulipan58",
  },
  find: {
    eyebrow_es: "encuentranos",
    eyebrow_en: "find us",
    title_es: "calle tulipan 58.",
    title_en: "58 tulipan street.",
    addressLabel_es: "direccion",
    addressLabel_en: "address",
    address: "calle tulipan 58, merida, yucatan, mx",
    hoursLabel_es: "horario",
    hoursLabel_en: "hours",
    hours1_es: "lun — sab · 7:30 a 20:00",
    hours1_en: "mon — sat · 7:30 to 20:00",
    hours2_es: "domingo · 8:00 a 14:00",
    hours2_en: "sunday · 8:00 to 14:00",
    contactLabel_es: "contacto",
    contactLabel_en: "contact",
    instagram: "@tulipan58mid",
    whatsapp: "+52 1 984 469 6732",
    website: "tulipan.mx",
    ctaMap_es: "abrir en mapas",
    ctaMap_en: "open in maps",
    ctaWa_es: "escribir por whatsapp",
    ctaWa_en: "message on whatsapp",
    mapLabel_es: "mapa · calle tulipan 58",
    mapLabel_en: "map · 58 tulipan street",
    mapsUrl: "https://maps.app.goo.gl/9UEggRyTwEoCW5sX6",
  },
  footer: {
    tagline_es: "el cafe que camina contigo.",
    tagline_en: "the coffee that walks with you.",
    navLabel_es: "navega",
    navLabel_en: "navigate",
    socialLabel_es: "siguenos",
    socialLabel_en: "follow",
    linksLabel_es: "sitio",
    linksLabel_en: "site",
    legal_es: "© tulipan58 · todos los derechos reservados · hecho despacio",
    legal_en: "© tulipan58 · all rights reserved · made slowly",
    credit_es: "crema sobre calle · merida, yucatan",
    credit_en: "cream on street · merida, yucatan",
  },
};
